name: 'Continuous Integrations'

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: 'Run ESLint and Prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the check scripts'
        run: 'bash run check'


  test:
    name: 'Run unit tests with Jest'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the test script'
        run: 'bash run test'

  bundle:
    name: 'Bundle package with Rollup.js'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the bundle script'
        run: 'bash run bundle'
